# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026, Minxi Hou <houminxi@gmail.com>
"""gate.yaml template for code-forge init."""

GATE_YAML_TEMPLATE = """\
# yaml-language-server: $schema=./gate.schema.json
# gate.yaml -- code-forge configuration
# Generated by: code-forge init

# outlet: review dispatch method
#   subprocess (default) -- spawns a fresh subprocess per review pass.
#                           Requires a backend under 'backends:' below.
#   inline              -- review runs in the current session (uses main quota).
#                           No subprocess, no reachability probe.
#   subagent            -- spawns a fresh Agent per pass; works inside the current
#                           session without a subprocess.
#   sampling            -- MCP only: borrows the IDE client's model, no API key.
# Note: 'cli' is a deprecated alias for 'subprocess' (emits a stderr warning).
# subprocess fails closed until a backend is configured under 'backends:'.
outlet: subprocess

# Cycle count adapts to diff size (relief, not defense):
#   <50 lines:  2 clean cycles (6 passes)
#   50-199:     3 clean cycles (9 passes, default)
#   >=200:      4 clean cycles (12 passes)
# Override: FORGE_CLEAN_ROUND_THRESHOLD=N

# backends: named review backends, keyed by name (dict, not list).
# Select a backend with FORGE_BACKEND=<name> or --backend <name>.
# Precedence: --backend flag > FORGE_BACKEND env > default: true entry > session-default.
#
# backends:
#   local-claude:
#     type: cli                   # 'cli' -- uses the claude binary in PATH
#     model: claude-sonnet-4-6    # optional: model to pass to CLI (omit = session default)
#     command: claude             # optional: CLI binary name or path (default: 'claude')
#     max_tokens: 16384           # optional: output token cap (default: 16384)
#     default: true               # optional: use this when no override is set
#
#   claude-api:
#     type: api                   # 'api' -- direct HTTP to an Anthropic-compatible endpoint
#     format: anthropic           # required for api: 'anthropic', 'openai', or 'vertex'
#     base_url: https://api.anthropic.com   # required for anthropic/openai format
#     api_key_env: ANTHROPIC_API_KEY        # required for anthropic/openai: env var NAME (not value)
#     model: claude-sonnet-4-6    # optional: model ID
#     max_tokens: 16384           # optional: output token cap (default: 16384)
#     default: false              # optional: Defaults to false
#
#   openai-compatible:
#     type: api
#     format: openai
#     base_url: https://api.openai.com/v1
#     api_key_env: OPENAI_API_KEY
#     model: gpt-4o
#     max_tokens: 8192
#
#   openrouter:                   # any OpenAI-compatible router/proxy works
#     type: api
#     format: openai              # OpenRouter speaks the OpenAI API
#     base_url: https://openrouter.ai/api/v1
#     api_key_env: OPENROUTER_API_KEY
#     model: anthropic/claude-sonnet-4.6   # use the router's prefixed model id
#     max_tokens: 16384
#
#   vertex-claude:
#     type: api                   # vertex is type: api, NOT type: cli
#     format: vertex              # required for Vertex AI backends
#     project_id: my-gcp-project  # required for vertex format
#     region: us-east5            # optional: GCP region (omit = global)
#     credentials_path: /path/to/sa-key.json  # optional: service account JSON path
#     model: claude-sonnet-4-6
#     max_tokens: 16384
#     reasoning_effort: high      # optional: nested as output_config.effort for vertex
#     thinking_type: adaptive     # optional: anthropic thinking control
#
#   # --- Provider-aware reasoning model examples ---
#   # Output cap: set the field that matches your provider's wire key.
#   #   max_completion_tokens: for OpenAI o-series, Kimi, MiMo (wire key auto-derived)
#   #   max_tokens: for DeepSeek, GLM, and legacy providers (wire key auto-derived)
#   # On openai format, forge sends whichever field you set -- one key, zero config.
#   # On anthropic/vertex format, the wire key is always max_tokens regardless.
#   # outcap_key: optional explicit override (rarely needed)
#
#   deepseek-r1:
#     type: api
#     format: openai
#     base_url: https://api.deepseek.com/v1
#     api_key_env: DEEPSEEK_API_KEY
#     model: deepseek-reasoner
#     max_tokens: 32768             # sets max_tokens field -> wire key is max_tokens
#     thinking_type: enabled
#     reasoning_effort: high
#     stream: true
#     timeout_s: 1800
#
#   mimo-pro:
#     type: api
#     format: anthropic
#     base_url: https://token-plan-cn.xiaomimimo.com/anthropic
#     api_key_env: MIMO_PRO_API_KEY
#     model: mimo-v2.5-pro
#     max_tokens: 16384
#     timeout_s: 1800
#
#   kimi-k2:
#     type: api
#     format: openai
#     base_url: https://api.kimi.com/coding/v1    # coding endpoint for review
#     api_key_env: KIMI_API_KEY
#     model: K2.7-Code
#     max_completion_tokens: 32768
#
#   minimax-m3:
#     type: api
#     format: anthropic             # MiniMax M3 speaks anthropic format
#     base_url: https://api.minimaxi.com/anthropic  # note: minimaxi (not minimax)
#     api_key_env: MINIMAX_API_KEY
#     model: MiniMax-M3
#     max_tokens: 16384
#     thinking_type: adaptive       # omit risks empty response on M3
#     timeout_s: 1800
#
#   glm-5:
#     type: api
#     format: openai
#     base_url: https://open.bigmodel.cn/api/paas/v4
#     api_key_env: GLM_API_KEY
#     model: glm-5.2
#     max_tokens: 32768             # sets max_tokens field -> wire key is max_tokens
#     thinking_type: enabled        # required for reasoning_effort on GLM
#     reasoning_effort: max
#     stream: true
#     timeout_s: 1800
#     # outcap_key: max_tokens     # optional explicit override (redundant here)
#
#   # --- CLI backend with env overrides ---
#   cli-with-env:
#     type: cli
#     command: claude
#     model: claude-sonnet-4-6
#     env:
#       unset: [ANTHROPIC_BASE_URL]  # remove proxy override from child
#       set:
#         ANTHROPIC_API_KEY_SOURCE: gate-yaml

# test: test command run by code-forge gate-check (R1 commit gate).
# Without this section, gate-check exits with an error.
# test:
#   command: [pytest, -q]         # required: list form, first element must be a known runner
#   timeout_seconds: 120          # optional: integer > 0 (default: 120)
#   env: {}                       # optional: extra env vars dict (omit = inherit shell env)
#   cwd: .                        # optional: working directory string (omit = repo root)
#   source_patterns: ["*.py"]     # optional: list of globs; gate skips if no staged file matches

# non_ascii: non-ASCII detection mode for commit messages and diffs.
#   ai-smell (default) -- blocks confusable typographic characters only
#                         (em dash, smart quotes, ellipsis, right arrow, NBSP).
#                         Accented letters, CJK, and emoji pass.
#   strict              -- blocks every non-ASCII byte.
# non_ascii: ai-smell

# presubmit: external linters run on staged diffs before the test gate.
# Each entry is run on the diff for files matching applies_to.
# presubmit:
#   - command: [ruff, check, --select=E,W]  # required: list form
#     applies_to: "*.py"                     # required: glob pattern
#     on: diff                               # required: 'diff' or 'patch'
#     when_exists: pyproject.toml            # optional: skip entry if this file is absent

# graph_triage: code-review-graph integration for impact-aware triage.
# graph_triage:
#   enabled: true                # optional: bool (omit = auto-detected)
#   db_path: .code-review-graph/graph.db  # optional: override graph.db path

# daemon_state: stateful subsystem conflict detection.
# daemon_state:
#   enabled: true                # optional: bool (omit = disabled)
#   subsystems: [networking]     # optional: state domains to focus on
#   patterns: []                 # optional: extra keyword patterns
#   conflicts_file: .code-forge/conflicts.yaml  # optional: external conflict triplets
#   conflicts:                   # optional: inline conflict triplets
#     - subsystem: networking    # required per triplet
#       mutates: routing_table   # required per triplet
#       interferes_with: firewall_rules  # required per triplet

# canary: opt-in reviewer laziness check (plants known-bad mutations).
# canary:
#   enabled: true
#   n: 5                    # canaries to plant (3..5)
#   threshold_ratio: 0.6   # catch ratio to pass (>0.0..1.0)
"""

CONTRACT_TEMPLATE_MD = """\
# Per-Change Intent Contract

## Invariants

<!-- What must remain true after this change? -->
<!-- Example: normalize() must preserve input ordering -->

## Residual Risks

<!-- What could still go wrong despite the change looking correct? -->
<!-- Example: concurrent callers may see stale cache entries -->

## Change Scope

<!-- What does this change do and what does it NOT do? -->
"""
