# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026, Minxi Hou <houminxi@gmail.com>
"""gate.yaml template for code-forge init."""

GATE_YAML_TEMPLATE = """\
# gate.yaml -- code-forge configuration
# Generated by: code-forge init

# outlet: review dispatch method
#   subprocess (default) -- fresh claude subprocess per review pass
#   inline -- review runs in the current session (uses main quota)
#   subagent -- fresh Agent per pass (no CLI overhead)
# outlet: subprocess

# Cycle count adapts to diff size (relief, not defense):
#   <50 lines:  2 clean cycles (6 passes)
#   50-199:     3 clean cycles (9 passes, default)
#   >=200:      4 clean cycles (12 passes)
# Override: FORGE_CLEAN_ROUND_THRESHOLD=N

backends:
  mimo:
    type: api
    format: anthropic
    model: mimo-v2.5-pro  # verify current model name at your provider console
    base_url: https://token-plan-cn.xiaomimimo.com/anthropic
    api_key_env: MIMO_API_KEY
    max_tokens: 16384
    default: true
  deepseek:
    type: api
    format: openai
    model: deepseek-v4-pro  # verify current model name at your provider console
    base_url: https://api.deepseek.com/v1
    api_key_env: DEEPSEEK_API_KEY
    max_tokens: 8192
  kimi:
    type: api
    format: anthropic
    model: kimi-k2.6  # verify current model name at your provider console
    base_url: https://api.moonshot.cn/anthropic
    api_key_env: KIMI_API_KEY
    max_tokens: 8192
  glm:
    type: api
    format: openai
    model: glm-4.5-air  # verify current model name at your provider console
    base_url: https://open.bigmodel.cn/api/paas/v4
    api_key_env: GLM_API_KEY
    max_tokens: 8192
  minimax:
    type: api
    format: anthropic
    model: MiniMax-M3  # verify current model name at your provider console
    base_url: https://api.minimaxi.com/anthropic
    api_key_env: MINIMAX_API_KEY
    max_tokens: 16384

# Vertex AI (Claude via GCP) -- cli backend with env vars:
#   Set these env vars before running code-forge:
#     CLAUDE_CODE_USE_VERTEX=true
#     ANTHROPIC_VERTEX_PROJECT_ID=your-project-id
#     CLOUD_ML_REGION=us-east5
#     GOOGLE_APPLICATION_CREDENTIALS=/path/to/sa-key.json
# vertex-claude:
#   type: cli
#   model: claude-sonnet-4-6

# test:
#   command: pytest
#   pattern: "*.py"
"""
