# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026, Minxi Hou <houminxi@gmail.com>
"""setup-mcp: one-command MCP onboarding for forge.

Writes user-level backend config, project-level gate.yaml (outlet + test
only, no backends), auto-trusts, and prints client registration command.
"""
from __future__ import annotations

import os
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class BackendPreset:
    """A known backend preset with verified endpoint and model."""

    name: str
    format: str
    base_url: str
    api_key_env: str
    model: str
    max_tokens: int
    timeout_s: int = 0  # 0 = use forge default; >0 = override per-backend


# Preset table: each entry verified against reference_llm_api_models.md
# (ground truth, user-corrected 2026-07-03).  No vertex (project-specific credentials).
PRESETS: dict[str, BackendPreset] = {
    "deepseek": BackendPreset(
        name="deepseek",
        format="openai",
        base_url="https://api.deepseek.com/v1",
        api_key_env="DEEPSEEK_API_KEY",
        model="deepseek-v4-flash",
        max_tokens=8192,
    ),
    "mimo-pro": BackendPreset(
        name="mimo-pro",
        format="anthropic",
        base_url="https://token-plan-cn.xiaomimimo.com/anthropic",
        api_key_env="MIMO_PRO_API_KEY",
        model="mimo-v2.5-pro",
        max_tokens=131072,
        timeout_s=1800,
    ),
    "kimi": BackendPreset(
        name="kimi",
        format="openai",
        base_url="https://api.kimi.com/coding/v1",
        api_key_env="KIMI_API_KEY",
        model="K2.7-Code",
        max_tokens=32768,
        timeout_s=1800,
    ),
    "minimax": BackendPreset(
        name="minimax",
        format="anthropic",
        base_url="https://api.minimaxi.com/anthropic",
        api_key_env="MINIMAX_API_KEY",
        model="MiniMax-M3",
        max_tokens=16384,
        timeout_s=1800,
    ),
    "glm": BackendPreset(
        name="glm",
        format="openai",
        base_url="https://open.bigmodel.cn/api/paas/v4",
        api_key_env="GLM_API_KEY",
        model="glm-5.2",
        max_tokens=32768,
        timeout_s=1800,
    ),
    "claude-api": BackendPreset(
        name="claude-api",
        format="anthropic",
        base_url="https://api.anthropic.com",
        api_key_env="ANTHROPIC_API_KEY",
        model="claude-sonnet-4-6",
        max_tokens=16384,
    ),
    "openai": BackendPreset(
        name="openai",
        format="openai",
        base_url="https://api.openai.com/v1",
        api_key_env="OPENAI_API_KEY",
        model="gpt-4.1-mini",
        max_tokens=16384,
    ),
}


def _detect_backends() -> list[BackendPreset]:
    """Auto-detect available backends by checking API key env vars."""
    return [p for p in PRESETS.values() if os.environ.get(p.api_key_env)]


def _render_user_config(presets: list[BackendPreset]) -> str:
    """Render user-level config.yaml content from selected presets."""
    import yaml as _y

    backends: dict[str, dict] = {}
    for i, p in enumerate(presets):
        entry: dict = {
            "type": "api",
            "format": p.format,
            "base_url": p.base_url,
            "api_key_env": p.api_key_env,
            "model": p.model,
            "max_tokens": p.max_tokens,
        }
        if p.timeout_s > 0:
            entry["timeout_s"] = p.timeout_s
        if i == 0:
            entry["default"] = True
        backends[p.name] = entry

    data = {"backends": backends}
    header = (
        "# User-level forge backend defaults\n"
        "# Generated by: code-forge setup-mcp\n"
        "# Shared across all projects via user_config loader.\n"
        "# API keys are referenced by env var name, never stored here.\n"
    )
    return header + _y.dump(data, default_flow_style=False, sort_keys=False)


# Minimal project gate.yaml: outlet + test only, no backends (C1).
PROJECT_GATE_TEMPLATE = """\
# Project-level forge config (backends live in user-level config)
# Generated by: code-forge setup-mcp
outlet: subprocess

test:
  command: [pytest, -q]
  timeout_seconds: 900
"""


def run_setup_mcp(
    cwd: Path,
    backend_names: list[str],
    force: bool = False,
    dry_run: bool = False,
) -> int:
    """Execute setup-mcp: write configs, trust, print registration.

    Returns 0 on success, 1 on error.
    """
    # Resolve presets
    if backend_names:
        presets = []
        seen: set[str] = set()
        for name in backend_names:
            if name not in PRESETS:
                print(
                    "Unknown backend preset '%s'. Available: %s"
                    % (name, ", ".join(sorted(PRESETS))),
                    file=sys.stderr,
                )
                return 1
            if name not in seen:
                presets.append(PRESETS[name])
                seen.add(name)
    else:
        presets = _detect_backends()
        if not presets:
            print(
                "No API keys detected in environment. "
                "Specify backends explicitly: "
                "code-forge setup-mcp --backend deepseek",
                file=sys.stderr,
            )
            return 1
        detected = ", ".join(p.name for p in presets)
        print("Detected backends: %s" % detected, file=sys.stderr)

    # Resolve user config directory (shared with user_config reader)
    from .user_config import user_config_dir

    config_dir = user_config_dir()
    user_cfg_path = config_dir / "config.yaml"
    gate_yaml_path = cwd / ".code-forge" / "gate.yaml"

    user_config_content = _render_user_config(presets)
    gate_content = PROJECT_GATE_TEMPLATE

    if dry_run:
        print("--- %s ---" % user_cfg_path, file=sys.stderr)
        print(user_config_content, file=sys.stderr)
        print("--- %s ---" % gate_yaml_path, file=sys.stderr)
        print(gate_content, file=sys.stderr)
        return 0

    # Write user-level config
    wrote_user = False
    if user_cfg_path.exists() and not force:
        print(
            "User config exists: %s (use --force to overwrite)" % user_cfg_path,
            file=sys.stderr,
        )
    else:
        config_dir.mkdir(parents=True, exist_ok=True)
        user_cfg_path.write_text(user_config_content, encoding="utf-8")
        wrote_user = True
        print("Wrote user config: %s" % user_cfg_path, file=sys.stderr)

    # Write project gate.yaml (no backends, C1)
    wrote_gate = False
    if gate_yaml_path.exists() and not force:
        print(
            "Project gate.yaml exists: %s (use --force to overwrite)"
            % gate_yaml_path,
            file=sys.stderr,
        )
    else:
        gate_yaml_path.parent.mkdir(parents=True, exist_ok=True)
        gate_yaml_path.write_text(gate_content, encoding="utf-8")
        wrote_gate = True
        print("Wrote project gate.yaml: %s" % gate_yaml_path, file=sys.stderr)

    # Auto-trust only what we just wrote (never blanket-trust existing files)
    if wrote_gate:
        import yaml as _y

        try:
            with open(gate_yaml_path, "r", encoding="utf-8") as f:
                gate_data = _y.safe_load(f) or {}
            from .trust import record_trust

            record_trust(gate_yaml_path, gate_data)
            print("Trusted: %s" % gate_yaml_path, file=sys.stderr)
        except Exception as exc:
            print(
                "Warning: gate.yaml written but trust recording failed: "
                "%s. Run 'code-forge trust' manually." % exc,
                file=sys.stderr,
            )

    # Print client registration command only when user config was written
    # (so env vars match the backends that will actually be loaded).
    if wrote_user:
        key_envs = " ".join(
            "-e %s=$%s" % (p.api_key_env, p.api_key_env) for p in presets
        )
        print(
            "\nSetup complete. Register the MCP server in your client:\n\n"
            "  claude mcp add forge %s -- code-forge-mcp\n" % key_envs,
            file=sys.stderr,
        )
    elif wrote_gate:
        print(
            "\nProject gate.yaml written. Existing user config kept at "
            "%s. Ensure its API keys are forwarded to the MCP server.\n"
            % user_cfg_path,
            file=sys.stderr,
        )
    else:
        print(
            "No files written (both exist). Use --force to overwrite.",
            file=sys.stderr,
        )

    return 0
