








































[options]
packages = find:
install_requires =
    appdirs>=1.4.0
    astroid>=2.6.5,<2.7 # (You should also upgrade requirements_test_min.txt)
    isort>=4.2.5,<6
    mccabe>=0.6,<0.7


























[isort]
multi_line_output = 3
line_length = 88
known_third_party = appdirs, astroid, sphinx, isort, pytest, mccabe, six, toml
include_trailing_comma = True
skip_glob = tests/functional/**,tests/input/**,tests/extensions/data/**,tests/regrtest_data/**,tests/data/**,astroid/**,venv/**
src_paths = pylint

[mypy]
scripts_are_modules = True

[mypy-appdirs]
ignore_missing_imports = True

[mypy-astroid.*]
ignore_missing_imports = True

